---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server
    - role: helm
    - role: rancher
    # - role: metallb
    # - role: nginx

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent
    - role: k3s_longhorn_agent

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_longhorn_server
    - role: metallb
