---
- name: Install Longhorn Server dependencies
  ansible.builtin.apt:
    name:
      - nfs-common
      - open-iscsi
      - util-linux
      - jq
    update_cache: true
    state: present

- name: Add Longhorn repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    create_namespace: true
    namespace: longhorn-system
    update_repo_cache: true
    wait: true

- name: Copy Longhorn Service Config
  ansible.builtin.template:
    src: longhorn.yml.j2
    dest: /root/longhorn.yml
    owner: root
    group: root
    mode: 0644
  register: longhorn_ingress_config

- name: Apply Longhorn Service
  ansible.builtin.command:
    cmd: kubectl apply -f /root/longhorn.yml
