---
- name: Install Longhorn Server dependencies
  ansible.builtin.apt:
    name:
      - nfs-common
      - open-iscsi
      - util-linux
      - jq
    update_cache: true
    state: present

- name: Add Longhorn repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    create_namespace: true
    namespace: longhorn-system
    update_repo_cache: true

# - name: Install Longhorn
#   command: >-
#     kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/deploy/longhorn.yaml

- name: Copy longhorn ingress
  ansible.builtin.template:
    src: longhorn-ingress.yml.j2
    dest: /root/longhorn-ingress.yml
    owner: root
    group: root
    mode: 0644
  register: longhorn_ingress_config

- name: Longhorn Ingress
  when: longhorn_ingress_config
  ansible.builtin.command:
    cmd: kubectl -n longhorn-system apply -f /root/longhorn-ingress.yml
  # changed_when: true
