---
- name: Add MetalLB Repository
  kubernetes.core.helm_repository:
    name: metallb
    force_update: true
    repo_url: "https://metallb.github.io/metallb"

- name: Install MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    create_namespace: true
    namespace: metallb-system
    update_repo_cache: true
    wait: true

- name: Copy MetalLB Service Config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: 'metallb-ip-address-pool.yml.j2', dest: '/root/metallb-ip-address-pool.yml' }
    - { src: 'metallb-l2.yml.j2', dest: '/root/metallb-l2.yml' }

- name: Apply MetalLB Service
  ansible.builtin.shell: |
    kubectl apply -f /root/metallb-ip-address-pool.yml
    kubectl apply -f /root/metallb-l2.yml 
