---
- name: Add MetalLB Repository
  kubernetes.core.helm_repository:
    name: metallb
    force_update: true
    repo_url: "https://metallb.github.io/metallb"

- name: Install MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    create_namespace: true
    namespace: metallb-system
    update_repo_cache: true
    wait: true

- name: Enable MetalLB
  ansible.builtin.shell: |
    cat << 'EOF' | kubectl apply -f -
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: default-pool
      namespace: metallb-system
    spec:
      addresses:
      - 192.168.0.200-192.168.0.250
    ---
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: default
      namespace: metallb-system
    spec:
      ipAddressPools:
      - default-pool
    EOF
